# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: chmod u+x build.sh
      - run: ./build.sh
